### ISSUE TITLE
Need to update the list of projects moved to Backdrop core

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/backdrop_upgrade_status#1]
These are all arrayed in `_backdrop_upgrade_status.module` in function `_backdrop_upgrade_status_d8_core()`. Please suggest in this issue, or better still, send a PR.

There is also a `_backdrop_upgrade_status_d7_core()` as well but probably unnecessary to bother with that.

**Comment by jenlampton** [comment]
I'm going to take a stab at updating this list with everything on https://backdropcms.org/upgrade-from-drupal/features-added-core.

**Comment by jenlampton** [comment]
Okay, [this PR](https://github.com/backdrop-contrib/backdrop_upgrade_status/pull/5) includes all 74 of the modules listed on that page as of 3/18.

**Comment by laryn** [comment]
Cross-referencing issues that are separate but related: https://github.com/backdrop-ops/backdropcms.org/issues/570
