### ISSUE TITLE
Include in the report if an upgrade path is available

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/backdrop_upgrade_status#10]
I'm wondering if its enough to just say that module has been integrated into Backdrop core, or replaced by another. We should also state in the report if there will be an automatic process during the upgrade or if user will need to do manual work.

For example: `Block Class Module` was 'Integrated into core Block module since v1.0' but user would still need to manually update block classes, whereas `Views` would upgrade automatically.

See also https://github.com/backdrop/backdrop-issues/issues/3680 which would go nicely with this effort

**Comment by jenlampton** [comment]
I've added both an `in_core_complete` property as well as `in_core_warning` that will allow us to indicate if something was completely included in core (as opposed to only partially) and to add any instructions or help text that may be necessary. 

I've gone ahead and added the following warning for `block_class`, but we can/should add others as we find them. 

```
Classes will need to be re-entered manually until https://github.com/backdrop/backdrop-issues/issues/5801 is resolved.
```
