### ISSUE TITLE
On drupal.org now - anyone else want to help?

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/backdrop_upgrade_status#13]
I created https://www.drupal.org/project/backdrop_upgrade_status - figured someone should just jump into the pool and test the waters.

I'm willing to put my name on here as maintainer, though I'll have to rely on others contributing PRs and testing. If people are okay with that then we keep this github as canonical and then sync the changes to drupal.org after

**Comment by herbdool** [comment]
Also I'd be happy if others also joined as maintainers. @laryn @jenlampton @philsward?

**Comment by laryn** [comment]
@herbdool I'd be happy to be listed and pitch in. Can you list my org as a supporting org as well?
https://www.drupal.org/stuart-center

**Comment by docwilmot** [comment]
Fantastic. I'd be happy to be listed, as the original porter. Have no orgs to list though.
> figured someone should just jump into the pool and test the waters.

As a practical life lesson though, jumping in the pool is not the recomended way to test the water, just saying. 😄

**Comment by stpaultim** [comment]
Is this something we are ready to Tweet about? and/or post on Facebook?

**Comment by oadaeh** [comment]
I signed up to receive e-mail notifications for all issues. That's about all I can commit to for now. I'll reply to any issues I do not feel will be a big time drain. :)
https://www.drupal.org/project/issues/subscribe-mail/backdrop_upgrade_status

**Comment by philsward** [comment]
@stpaultim I would like to discuss the telemetry addon before making it "public", that way it's in everyone's face after they install it.

Hate to have it get out on 1000 sites and not be able to collect data on it.

Don't let my wishes stop anyone though.

@docwilmot (and anyone else interested) we need to get together and set aside some time to work on the telemetry idea. Be thinking about some time we can schedule for this to hammer it out.

**Comment by docwilmot** [comment]
@philsward I dont think we should delay this actually. Anyone who uses this *now* is someone who is a potential Backdropper who needs the info *now*. Delaying it doesn't help us or them. Let's get this out there.

**Comment by stpaultim** [comment]
> I would like to discuss the telemetry addon before making it "public", that way it's in everyone's face after they install it.

I agree that we should not wait on telemetry. Which is too late anyway, since it seems to me like its up there on Drupal.org already. Again, I am highly skeptical that we need to worry about too many people using it too quickly AND I think it's better to have folks using the module without collecting any data than to have them not using it at all. 

Is there any reason to NOT tweet about it yet?

(@philsward - I'll be happy to get a handful of people looking at it in the next few weeks, even with a Tweet and/or Facebook post. I wouldn't worry about too many people downloading it immediately. If that happens, well it will be a nice problem to have.). 

Tweeting about it might get a few people to look at it and report any problems they have.

**Comment by philsward** [comment]
@stpaultim "Leroy Jenkins"

Get it done.

**Comment by jenlampton** [comment]
I'd be happy to help maintain on d.o too. Thanks to all of you for moving this forward again and for all the offers to help support!

**Comment by herbdool** [comment]
I've added @laryn @jenlampton @docwilmot as maintainers in d.org.

I already made a release so the cat is out of the bag.

@docwilmot yes! Me mixing metaphors. I guess it's me saying I'm being foolhardy.

**Comment by herbdool** [comment]
I've synced the repos now - git histories should now match.

**Comment by laryn** [comment]
@herbdool I added "Backdrop CMS" as a supporting org so BUS shows up on the Backdrop page:

 - https://www.drupal.org/backdrop-cms

**Comment by Wylbur** [comment]
@herbdool Please add me as a contributor!

**Comment by herbdool** [comment]
@Wylbur you want access to this repo and/or on drupal.org?

**Comment by Wylbur** [comment]
I'm a maintainer on d.o, thanks.  I am closing this ticket now.
