### ISSUE TITLE
Issues with constants

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/backdrop_upgrade_status#15]
After disabling, many of these in the log:

> Warning: Use of undefined constant BACKDROP_UPGRADE_UPDATE_DEFAULT_URL - assumed 'BACKDROP_UPGRADE_UPDATE_DEFAULT_URL' (this will throw an Error in a future version of PHP) in _backdrop_upgrade_status_build_fetch_url_backdrop() (line 294 of /app/sites/all/modules/backdrop_upgrade_status/backdrop_upgrade_status.fetch.inc).

**Comment by laryn** [comment]
Speaking of constants, this should not be `8.x`:

> define('BACKDROP_UPGRADE_STATUS_CORE_VERSION', '8.x');

Although it looks like it may be considering Backdrop as 8.x here:
https://github.com/backdrop-contrib/backdrop_upgrade_status/blob/7.x-1.x/backdrop_upgrade_status.module#L277-L298

**Comment by herbdool** [comment]
I think this is fixed by https://github.com/backdrop-contrib/backdrop_upgrade_status/commit/48eb1bd9a35235911b4588d747a300b0a733761c
