### ISSUE TITLE
Need to update the list of projects who's names were changed while porting to Backdrop

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/backdrop_upgrade_status#2]
These are all arrayed in `backdrop_upgrade_status.compare.inc` in function `backdrop_upgrade_status_obsolete()`. Please suggest in this issue, or better still, send a PR.

For example `Profile 2` is renamed to `Profile`

**Comment by laryn** [comment]
- `google_analytics` => `googleanalytics`
 - `imagecache_actions` => `image_effects`
- `linkit` => partially in core

**Comment by herbdool** [comment]
I've added @laryn's list here https://github.com/backdrop-contrib/backdrop_upgrade_status/commit/6f7faac4839798e59455f4fb81534adfd9fe6c67. `linkit` actually goes into `_backdrop_upgrade_status_backdrop_core()` since it's in core.
