### ISSUE TITLE
Views Data - do not report that disabled modules in code need to be edited and saved 

### ISSUE THREAD

**Issue by Wylbur** [backdrop-contrib/backdrop_upgrade_status#21]
![Screenshot from 2021-11-03 15-08-51](https://user-images.githubusercontent.com/238274/140185024-c339dc90-e22b-48b8-8dda-61efb2bb2718.jpg)

**Comment by Wylbur** [comment]
Here's an updated screenshot showing how the Views Data section looks with disabled views.  
![Screenshot from 2021-12-15 00-29-18](https://user-images.githubusercontent.com/238274/146135288-318d82fe-3a51-47ab-9ddf-fd83e5ad77ed.png)

**Comment by Wylbur** [comment]
@jenlampton  I created some logic to display disabled views with warning styling, and provided a link back to the views admin page to be able to enable views if needed for a port.  Let me know if this is a good approach!

**Comment by jenlampton** [comment]
Thanks for the PR @Wylbur !  This is a great improvement, and will be included in the next release :)
