### ISSUE TITLE
Status of Workflow module: showing Drupal 8 related information

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/backdrop_upgrade_status#23]
I have the [Workflow](https://www.drupal.org/project/workflow) module on a Drupal 7 site. The Backdrop Upgrade Status claims that Workflow is in "Backdrop core since **8.5**" and links to a [Drupal 8 content moderation documentation](https://www.drupal.org/docs/8/core/modules/content-moderation/overview) page. Version number 8.5 and the documentation are related to Drupal 8 but not to Backdrop.

PS: I'm using v 7.x-1.1 of Backdrop Upgrade Status [hosted on drupal.org](https://www.drupal.org/project/backdrop_upgrade_status).

**Comment by olafgrabienski** [comment]
Similar but slightly better the Pathauto information:

> In Backdrop core since 8.5
> Integrated into core Path module in v1.11

**Comment by jenlampton** [comment]
strange! Can you test the new 7.x-1.2 release and see if that fixes it for you?

**Comment by olafgrabienski** [comment]
> Can you test the new 7.x-1.2 release and see if that fixes it for you?

In the meantime, I've upgraded the D7 site to Backdrop, so I can't test at the moment. I'll try to have another look at the next opportunity.

**Comment by jenlampton** [comment]
> In the meantime, I've upgraded the D7 site to Backdrop

That's even better! :)

**Comment by jenlampton** [comment]
There was some old code from the Drupal module causing this problem. I fixed it in 35ae6969719517 by commenting out the Drupal code. This should be fixed in the next release.
