### ISSUE TITLE
Failed to get available update data

### ISSUE THREAD

**Issue by echozone** [backdrop-contrib/backdrop_upgrade_status#26]
Backdrop upgrade status 7.x-1.1
running on Drupal 7.84

Failed to get available update data on all projects (except Google Analytics!)

It has worked previously, now consistently failing.
Tested multiple times, on local + live site.

dblog shows a series of Undefined Index, one for backdrop_upgrade_status.fetch.inc, the rest for backdrop_upgrade_status.report.inc

and 2 Warnings, 

Warning: sort() expects parameter 1 to be array, null given in theme_backdrop_upgrade_status_report() (line 275 of ___backdrop_upgrade_status.report.inc

Warning: implode(): Invalid arguments passed in theme_backdrop_upgrade_status_report() (line 276 of ___backdrop_upgrade_status.report.inc

**Comment by Wylbur** [comment]
@echozone Try the DEV branch of the module, this is being actively worked on, so lots of fixes and updates have been applied that are not part of the stable release.

**Comment by echozone** [comment]
Thx @Wylbur Had done that + did again, with complete disabling, clearing caches,
_ same result _
Same notices + warnings, just with expected different line #s.
Is this really just me?

**Comment by Wylbur** [comment]
@echozone I am also getting notices about missing indexes and accessing array variables.  

Can you include a screenshot, or add the error message text here?

Some of mine are showing errors in the site data.  For example - I had Poll module enabled, and removed all polls and disabled/uninstalled the module.  However now the site has an orphaned poll bundle that is triggering the errors.  

I'll try and add issues and fixes and copy you on those.  

In the meantime, the module is still working for me, since all my notices are warnings instead of errors.

**Comment by echozone** [comment]
I did see the new overview report, very nice! but it still shows all contrib modules with unknown status. Here's all Notices + warnings in order:

Notice: Undefined index: title in theme_backdrop_upgrade_status_report() (line 261 of /PATH_TO/backdrop_upgrade_status.report.inc).

Notice: Undefined index: link in theme_backdrop_upgrade_status_report() (line 261 of /PATH_TO/backdrop_upgrade_status.report.inc).

Notice: Undefined index: recommended in theme_backdrop_upgrade_status_report() (line 261 of /PATH_TO/backdrop_upgrade_status.report.inc).

Notice: Undefined index: name in theme_backdrop_upgrade_status_report() (line 78 of /PATH_TO/backdrop_upgrade_status.report.inc).

Notice: Undefined index: name in theme_backdrop_upgrade_status_report() (line 78 of /PATH_TO/backdrop_upgrade_status.report.inc).

Notice: Undefined index: name in theme_backdrop_upgrade_status_report() (line 153 of /PATH_TO/backdrop_upgrade_status.report.inc).

Notice: Undefined index: name in theme_backdrop_upgrade_status_report() (line 163 of /PATH_TO/backdrop_upgrade_status.report.inc).

Warning: sort() expects parameter 1 to be array, null given in theme_backdrop_upgrade_status_report() (line 279 of /PATH_TO/backdrop_upgrade_status.report.inc).

Warning: implode(): Invalid arguments passed in theme_backdrop_upgrade_status_report() (line 280 of /PATH_TO/backdrop_upgrade_status.report.inc).

Notice: Undefined index: project_type in theme_backdrop_upgrade_status_report() (line 313 of /PATH_TO/backdrop_upgrade_status.report.inc).

Notice: Undefined index: project_type in theme_backdrop_upgrade_status_report() (line 314 of /PATH_TO/backdrop_upgrade_status.report.inc).

Notice: Undefined index: name in theme_backdrop_upgrade_status_report() (line 316 of /PATH_TO/backdrop_upgrade_status.report.inc).

Notice: Undefined index: project_type in theme_backdrop_upgrade_status_report() (line 317 of /PATH_TO/backdrop_upgrade_status.report.inc).

**Comment by eleven3** [comment]
I am having the same problem as echozone, for all modules it says "Failed to get available update data."
No php errors or warnings. 
And the DEV version mentioned, where do I go to get that and try it?

**Comment by echozone** [comment]
The main "Code" tab, the green "Code" button dropdown, "Download ZIP" link.

That's where I found it, I'd welcome anyone pointing us to a more elegant location :-)

**Comment by Wylbur** [comment]
@eleven3 @echozone 
Can you tell me more about the environment where you are getting this error?  
- Is this on the LIVE site?  If so, what hosting service are you using.  
- Is this on a local machine? If so, what stack is being used.  

I'll test locally, and on a server to see if I can replicate.

**Comment by Wylbur** [comment]
I tested this on an existing site.  

LIVE site - was able to install module, then run the update status
/admin/reports/updates/backdrop-upgrade
When I landed on this page, no updates were available, BUT I was able to click "Check manually" and it pulled all the updates.  

Local site - also tested on a local site using Docksal.  

@eleven3 @echozone 
Another question - can you get Drupal update status? 
/admin/reports/updates

**Comment by echozone** [comment]
Thx for testing @Wylbur. I have been running the dev version from 11/3, on 2 locals + their 2 live sites. Previously the locals failed with no notices or warnings, but today got the warning as in issue #16 (headers already sent). Yes, I can, and always did get the regular Drupal update status.

local:
site 1 php 7.2.1  MySQL 5.6.38
site 2 php 7.2.1  MySQL 5.6.38

live:
site 1 php 7.1.33  MySQL 5.5.5-10.1.43-MariaDB
site 2 php 7.2.34  MySQL 5.6.47 *worked*

Today, as mostly done in the past, completely disabled, uninstalled, removed, re-installed, flushed cache, ran cron using long link "run cron from outside the site" (new step) and all failed as usual _except_  site 2 successfully ran the module :-)

I need it on both, and hope it get's some love. The packaging script or related is also not right, as it doesn't list the version on the modules screen.

**Comment by Wylbur** [comment]
@echozone 
That's very helpful. Couple of things:
- the dev version does not have a defined version, so that is normal
- I tested using php 7.2, and mysql 5.6, and had no issues

When you reinstall, do you completely remove the old module folder?  

Have you upgraded to the latest version of Drupal core and modules?

It sounds like you are experiencing the issue from issue #16 .  Disabling and uninstalling the module then reinstalling the new version should resolve this.  

Are you able to run cron before and after the module is installed?  Can you run cron over and over again?

Have you also run update.php?

**Comment by echozone** [comment]
As I wrote last post, 
"as mostly done in the past, completely disabled, uninstalled, removed, re-installed, flushed cache, ran cron using long link "run cron from outside the site" (new step) and all failed as usual except site 2 successfully ran the module" 
so I already did what you've asked, except this time, I've done all the things plus update.php and yes I can run cron before + after.

My OP says core is up to date, and the failed live site only has the latest Commerce not updated.

**Comment by echozone** [comment]
Upgraded to -

php 7.4.21
MySQL 5.7.34

and BUS now working :-)
