### ISSUE TITLE
This module sometimes makes dangerous / misleading suggestions

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/backdrop_upgrade_status#28]
From our Zulip chat:

```
the amazing backdrop-upgrade report says: disable and uninstall module Variable in my drupal 7. Is that a mistake? Lots of other modules with "leave enabled" depend on it.
```

The depending module(s) are i18n (mostly) - but in an update hook i18n grabs data from the variable_store table to not lose them.

So suggesting to uninstall the Variable module on D7 already, can lead to data loss.

**Comment by jenlampton** [comment]
Yes, if the variable module deletes anything when uninstalled, that would be dangerous. I'll update the recommendation to leave enabled. Having data in that table in backdrop is also not a risk. It's definitely safer to leave it than loose something!
