### ISSUE TITLE
"run cron" does nothing.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/backdrop_upgrade_status#3]
I have done the following:

1. Installed a fresh copy of the module (on an almost vanilla D7 site; just `admin_menu` and `devel` contrib modules).
2. Navigated to `admin/reports/updates/backdrop-upgrade`
3. Saw the "No upgrade information available. [Run cron](url) or [check manually](url)" message -> clicked "run cron" -> nothing 👎 -> refreshed the page -> nothing 👎 
4. Clicked "check manually" -> success 👍

**Comment by jenlampton** [comment]
There's no `hook_cron()` for this module, so cron won't do anything. Let me see if I can add one...
