### ISSUE TITLE
No contrib modules listed until manually populated

### ISSUE THREAD

**Issue by xurizaemon** [backdrop-contrib/backdrop_upgrade_status#30]
I'm not sure what happened on the site I tried, but the contrib modules statuses weren't updated for me.

This meant that the TODO list at top of `/admin/reports/backdrop-upgrade` listed "Review [contrib modules](http://example.org/admin/reports/backdrop-upgrade#edit-contrib-modules): Disable and uninstall anthing not in use, or nolonger necessary." but the section itself was missing.

I traced my way through how this should be populated, and tried running update status checker and Drupal cron. No dice. (Maybe something else in cron killed it, could be an edge case.)

My suggestion is that where the data is not yet present, we add a placeholder that communicates this (and the appropriate action) to the user.

I worked around it using `drush core-cli` and `backdrop_upgrade_status_fetch_data();` to populate the cache.

**Comment by xurizaemon** [comment]
Text in PR is a placeholder for some TBC placeholder copy, hoping to better illustrate what I'm suggesting 😄

**Comment by xurizaemon** [comment]
Also, it's very likely I've done something wrong in trying to use the upgrade status report, this is the first site I've run it on.

I have Backdrop Upgrade Status 7.x-1.2 via Drupal.org

**Comment by jenlampton** [comment]
Thanks @xurizaemon!  I've merged your PR, and filed a follow-up commit to change "Here\'s what to do about it." into some text and a link, to help resolve the issue!
