### ISSUE TITLE
Potential query against non-existant table

### ISSUE THREAD

**Issue by jimmynash** [backdrop-contrib/backdrop_upgrade_status#34]
In includes/backdrop_upgrade_status.field.inc there is a count of the field data run against the field_data_ table for a field.

I ran into a situation where the node_display_fields module was in use. That module doesn't create a field_data_ table for it's fields so running the backdrop upgrade overview report throws a fatal error that the table doesn't exist.

We could wrap it in a check for the table maybe like so?

```php
        // Add the item count.
        $table = 'field_data_' . $field_name;
        if (db_table_exists($table)) {
          $count = db_query("SELECT count(entity_id) FROM {$table}")->fetchField();
          $rows[$field_name]['data']['count'] = $count;
          $rows[$field_name]['data']['recommendation'] = '';
          if ($count == 0) {
            $rows[$field_name]['class'] = array('warning');
            $rows[$field_name]['data']['recommendation'] = t('Delete this field?');
          }
        }
```

**Comment by jenlampton** [comment]
I love this recommendation, thank you!

**Comment by jenlampton** [comment]
Committed :)
