### ISSUE TITLE
Warning: Undefined array keys

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/backdrop_upgrade_status#40]
> Warning: Undefined array key "title" in theme_backdrop_upgrade_status_report() (line 260 of /var/www/html/drupal/sites/all/modules/contrib/backdrop_upgrade_status/backdrop_upgrade_status.report.inc).
> Warning: Undefined array key "link" in theme_backdrop_upgrade_status_report() (line 260 of /var/www/html/drupal/sites/all/modules/contrib/backdrop_upgrade_status/backdrop_upgrade_status.report.inc).
> Warning: Undefined array key "recommended" in theme_backdrop_upgrade_status_report() (line 260 of /var/www/html/drupal/sites/all/modules/contrib/backdrop_upgrade_status/backdrop_upgrade_status.report.inc).
> Warning: Undefined array key "name" in theme_backdrop_upgrade_status_report() (line 75 of /var/www/html/drupal/sites/all/modules/contrib/backdrop_upgrade_status/backdrop_upgrade_status.report.inc).
> Warning: Undefined array key "name" in theme_backdrop_upgrade_status_report() (line 150 of /var/www/html/drupal/sites/all/modules/contrib/backdrop_upgrade_status/backdrop_upgrade_status.report.inc).
> Warning: Undefined array key "name" in theme_backdrop_upgrade_status_report() (line 160 of /var/www/html/drupal/sites/all/modules/contrib/backdrop_upgrade_status/backdrop_upgrade_status.report.inc).
> Warning: Undefined array key "project_type" in theme_backdrop_upgrade_status_report() (line 312 of /var/www/html/drupal/sites/all/modules/contrib/backdrop_upgrade_status/backdrop_upgrade_status.report.inc).
> Warning: Undefined array key "project_type" in theme_backdrop_upgrade_status_report() (line 313 of /var/www/html/drupal/sites/all/modules/contrib/backdrop_upgrade_status/backdrop_upgrade_status.report.inc).
> Warning: Undefined array key "name" in theme_backdrop_upgrade_status_report() (line 315 of /var/www/html/drupal/sites/all/modules/contrib/backdrop_upgrade_status/backdrop_upgrade_status.report.inc).
> Warning: Undefined array key "project_type" in theme_backdrop_upgrade_status_report() (line 316 of /var/www/html/drupal/sites/all/modules/contrib/backdrop_upgrade_status/backdrop_upgrade_status.report.inc).

**Comment by laryn** [comment]
I suspect this is related to the local site also reporting:

> Failed to get available update data for 94 projects.

I'm not sure why it can't get data on so many projects...

**Comment by jenlampton** [comment]
I think I got all these, but if you get them again please open a new issue.
