### ISSUE TITLE
Warning icon when modules are available?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/backdrop_upgrade_status#7]
Currently it shows a warning icon if modules are available. 

![Screenshot_2020-11-13 Available updates Drupal7](https://user-images.githubusercontent.com/871421/99110001-5033ab00-25af-11eb-906d-27352038668d.png)

This should probably be the same checkmark used in the module list when a module is up to date:

![Screenshot_2020-11-13 Available updates Drupal7(1)](https://user-images.githubusercontent.com/871421/99110041-604b8a80-25af-11eb-9029-5cd2abc181e2.png)

**Comment by herbdool** [comment]
I think https://github.com/backdrop-contrib/backdrop_upgrade_status/commit/9d089c0be25b5dc97f9520ae081fa1006b071ff8 fixes this. The logic is quite messy but I didn't refactor it all. Just made sure it was checking for the right things.

If it's partially in core or if its name changed it'll still show a warning.

![Screenshot from 2020-12-16 12-25-09](https://user-images.githubusercontent.com/1071483/102383691-d4f05b00-3f99-11eb-8267-e991ecad6daf.png)

and

![Screenshot from 2020-12-16 12-26-54](https://user-images.githubusercontent.com/1071483/102383859-049f6300-3f9a-11eb-8dfb-8244eabbf4e5.png)
